image: docker:20.10

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - Assignment-1/Express/node_modules/

services:
  - docker:20.10-dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker info

build:
  stage: build
  script:
    - cd Assignment-1/Express/
    - docker build -t fly-with-confidence -f Dockerfile.build .
  artifacts:
    paths:
      - Assignment-1/Express/build
    expire_in: 1 week

test_lint:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - Assignment-1/Express/node_modules/
  script:
    - docker build -t fly-with-confidence -f Dockerfile.test .
    - docker run fly-with-confidence npm run lint

test_api:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - Assignment-1/Express/node_modules/
  script:
    - docker build -t fly-with-confidence -f Dockerfile.test .
    - docker run fly-with-confidence npm run test
  when: manual

deploy_dockerhub:
  stage: deploy
  script:
    - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE" -f Dockerfile.deploy .
    - docker push "$CI_REGISTRY_IMAGE"
  when: manual
