version: '8.1.0'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_HOST: deno-mysql-1
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myusername
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
  deno:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
